stages:
- name: compile
  steps:
  - runScriptConfig:
      image: maven:3.6.3-openjdk-8-slim
      shellScript: mvn clean package -Dmaven.test.skip=true
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: demo:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34040
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    when:
      branch:
        exclude:
        - master
timeout: 60
branch:
  include:
  - master
notification: {}
