stages:
- name: compile
  steps:
  - runScriptConfig:
      image: maven:3.6.3-openjdk-8-slim
      shellScript: mvn clean package -Dmaven.test.skip=true
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: registry.baison.net:9443/e3plus2.0/demo:${CICD_GIT_BRANCH}-${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: registry.baison.net:9443
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    when:
      branch: {}
timeout: 60
branch:
  include:
  - master
notification: {}
