apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: work1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-work1-demo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-work1-demo
    spec:
      containers:
      - image: 139.217.216.47:8081/e3plus2.0/demo:${CICD_GIT_BRANCH}-${CICD_EXECUTION_SEQUENCE}
        imagePullPolicy: Always
        name: demo
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: baison
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
